language: cpp
compiler:
    - g++

install:
    # get c++11 support
    - export CXX="g++-5" CC="gcc-5"
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - boost-latest
        packages:
            - gcc-5
            - g++-5

script:
    - make benchmark-all
